Refactor some utilities for fun and profit

diff --git a/bin/isup b/bin/isup
--- a/bin/isup
+++ b/bin/isup
@@ -3,12 +3,9 @@
 # check if a website is up
 # depends on the lynx text browser
 
-_lynx=$(which lynx) || exit 1
-_isup="http://www.downforeveryoneorjustme.com"
+hash lynx &>/dev/null || { echo "Cannot find lynx"; exit 1; }
+[[ -z "$1" ]] && { echo "You must give a URL to check if it is up"; exit 1; }
 
-if [[ -z ${1} ]]; then
-    echo "Must supply a URL to check..."
-    exit 1
-fi
+ISUP_URL="http://www.downforeveryoneorjustme.com"
 
-${_lynx} -dump "${_isup}/${1}" | head -1 | sed 's/...//' | sed 's/\[1\]//'
+lynx -dump "$ISUP_URL/${1}" | head -1 | sed 's/...//' | sed 's/\[1\]//'
